"""
create_fer_project_structure.py

Run this once to generate the full folder + file structure for the
EfficientNet-B0 Facial Emotion Recognition project.

Usage:
    python create_fer_project_structure.py [target_dir]

If target_dir is omitted, it creates ./fer_project in the current directory.
"""

import os
import sys

CLASSES = ["angry", "disgust", "fear", "happy", "neutral", "sad", "surprise"]

# ---------------------------------------------------------------------------
# File contents (kept minimal but functional/valid so files aren't empty stubs)
# ---------------------------------------------------------------------------

FILES = {

"requirements.txt": """torch>=2.1.0
torchvision>=0.16.0
timm>=0.9.12
opencv-python>=4.9.0
mediapipe>=0.10.9
numpy>=1.26.0
pandas>=2.1.0
scikit-learn>=1.3.0
matplotlib>=3.8.0
seaborn>=0.13.0
Pillow>=10.1.0
PyYAML>=6.0.1
requests>=2.31.0
fastapi>=0.109.0
uvicorn>=0.27.0
tensorboard>=2.15.0
tqdm>=4.66.0
""",

"README.md": """# Facial Emotion Recognition (EfficientNet-B0)

Project structure generated by `create_fer_project_structure.py`.

## Setup
```
pip install -r requirements.txt
```

## Workflow
1. Place FER2013 / CK+ / RAF-DB raw data in `dataset/raw/`
2. Run preprocessing to populate `dataset/processed/{train,validation,test}/<class>/`
3. `python train.py` to train
4. `python predict.py --image path/to/img.jpg` to test on a single image
5. `python app.py` to run webcam + backend pipeline

## Folder map
- `src/data` — Dataset, DataLoader, transforms
- `src/model` — EfficientNet-B0 definition
- `src/training` — train/evaluate loops
- `src/inference` — image/webcam inference, face detection, temporal smoothing
- `src/backend` — API client, session store, decision engine
- `configs/config.yaml` — all paths & hyperparameters
- `saved_models/` — checkpoints
""",

".gitignore": """__pycache__/
*.pyc
dataset/raw/
dataset/processed/
saved_models/*.pth
logs/
.env
.ipynb_checkpoints/
""",

"configs/config.yaml": """project_name: "AI Mental Wellness - Facial Emotion Recognition"

paths:
  train_dir: "dataset/processed/train"
  val_dir: "dataset/processed/validation"
  test_dir: "dataset/processed/test"
  checkpoint_dir: "saved_models"
  log_dir: "logs"

classes:
  - angry
  - disgust
  - fear
  - happy
  - neutral
  - sad
  - surprise

model:
  name: "efficientnet_b0"
  pretrained: true
  num_classes: 7
  input_size: 224

training:
  batch_size: 32
  num_epochs: 30
  learning_rate: 0.0003
  weight_decay: 0.00001
  optimizer: "adamw"
  scheduler: "cosine"
  early_stopping_patience: 7
  num_workers: 4
  device: "cuda"

augmentation:
  horizontal_flip_prob: 0.5
  rotation_degrees: 10
  brightness: 0.2
  contrast: 0.2

inference:
  smoothing_window: 8
  face_detection_confidence: 0.6
  webcam_index: 0
  frame_skip: 2

backend:
  api_base_url: "http://localhost:8000"
  emotion_endpoint: "/api/sessions/{session_id}/emotions"
  timeout_seconds: 5
""",

"src/__init__.py": "",
"src/data/__init__.py": "",
"src/model/__init__.py": "",
"src/training/__init__.py": "",
"src/inference/__init__.py": "",
"src/backend/__init__.py": "",

"src/config_loader.py": '''"""Loads configs/config.yaml into a dot-accessible object."""
import yaml
from pathlib import Path


class DotDict(dict):
    def __getattr__(self, key):
        try:
            value = self[key]
        except KeyError as e:
            raise AttributeError(key) from e
        if isinstance(value, dict):
            value = DotDict(value)
        return value

    def __setattr__(self, key, value):
        self[key] = value


def load_config(config_path: str = None) -> DotDict:
    if config_path is None:
        root = Path(__file__).resolve().parent.parent
        config_path = root / "configs" / "config.yaml"
    with open(config_path, "r") as f:
        raw = yaml.safe_load(f)
    return DotDict(raw)
''',

"src/data/transforms.py": '''"""Resize, normalize, and augmentation transforms (Phase 3)."""
from torchvision import transforms

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]


def get_train_transforms(cfg):
    size = cfg.model.input_size
    aug = cfg.augmentation
    return transforms.Compose([
        transforms.Resize((size, size)),
        transforms.RandomHorizontalFlip(p=aug.horizontal_flip_prob),
        transforms.RandomRotation(aug.rotation_degrees),
        transforms.ColorJitter(brightness=aug.brightness, contrast=aug.contrast),
        transforms.ToTensor(),
        transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
    ])


def get_eval_transforms(cfg):
    size = cfg.model.input_size
    return transforms.Compose([
        transforms.Resize((size, size)),
        transforms.ToTensor(),
        transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
    ])
''',

"src/data/dataset.py": '''"""Dataset / DataLoader construction (Phase 2-3)."""
from torch.utils.data import DataLoader
from torchvision.datasets import ImageFolder

from src.data.transforms import get_train_transforms, get_eval_transforms


def build_dataloaders(cfg):
    train_ds = ImageFolder(cfg.paths.train_dir, transform=get_train_transforms(cfg))
    val_ds = ImageFolder(cfg.paths.val_dir, transform=get_eval_transforms(cfg))
    test_ds = ImageFolder(cfg.paths.test_dir, transform=get_eval_transforms(cfg))

    train_loader = DataLoader(
        train_ds, batch_size=cfg.training.batch_size, shuffle=True,
        num_workers=cfg.training.num_workers, pin_memory=True,
    )
    val_loader = DataLoader(
        val_ds, batch_size=cfg.training.batch_size, shuffle=False,
        num_workers=cfg.training.num_workers, pin_memory=True,
    )
    test_loader = DataLoader(
        test_ds, batch_size=cfg.training.batch_size, shuffle=False,
        num_workers=cfg.training.num_workers, pin_memory=True,
    )
    return train_loader, val_loader, test_loader, train_ds.classes
''',

"src/model/efficientnet_b0.py": '''"""EfficientNet-B0 with a replaced 7-class classification head (Phase 4)."""
import torch.nn as nn
from torchvision.models import efficientnet_b0, EfficientNet_B0_Weights


def build_model(cfg):
    weights = EfficientNet_B0_Weights.DEFAULT if cfg.model.pretrained else None
    model = efficientnet_b0(weights=weights)

    in_features = model.classifier[1].in_features
    model.classifier[1] = nn.Linear(in_features, cfg.model.num_classes)

    return model
''',

"src/training/train.py": '''"""Training loop (Phase 5). Entry point: /train.py at project root."""
import os
import torch
import torch.nn as nn
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR
from tqdm import tqdm

from src.config_loader import load_config
from src.data.dataset import build_dataloaders
from src.model.efficientnet_b0 import build_model
from src.training.evaluate import evaluate


def get_device(cfg):
    if cfg.training.device == "cuda" and torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")


def train():
    cfg = load_config()
    device = get_device(cfg)
    print(f"Using device: {device}")

    train_loader, val_loader, _, classes = build_dataloaders(cfg)
    print(f"Classes: {classes}")

    model = build_model(cfg).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = AdamW(
        model.parameters(),
        lr=cfg.training.learning_rate,
        weight_decay=cfg.training.weight_decay,
    )
    scheduler = CosineAnnealingLR(optimizer, T_max=cfg.training.num_epochs)

    os.makedirs(cfg.paths.checkpoint_dir, exist_ok=True)
    best_val_acc = 0.0
    epochs_no_improve = 0

    for epoch in range(1, cfg.training.num_epochs + 1):
        model.train()
        running_loss, correct, total = 0.0, 0, 0

        loop = tqdm(train_loader, desc=f"Epoch {epoch}/{cfg.training.num_epochs}")
        for images, labels in loop:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item() * images.size(0)
            preds = outputs.argmax(dim=1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

            loop.set_postfix(loss=loss.item())

        scheduler.step()
        train_loss = running_loss / total
        train_acc = correct / total

        val_loss, val_acc, _, _, _ = evaluate(model, val_loader, criterion, device)
        print(f"Epoch {epoch}: train_loss={train_loss:.4f} train_acc={train_acc:.4f} "
              f"val_loss={val_loss:.4f} val_acc={val_acc:.4f}")

        if val_acc > best_val_acc:
            best_val_acc = val_acc
            epochs_no_improve = 0
            ckpt_path = os.path.join(cfg.paths.checkpoint_dir, "emotion_model_best.pth")
            torch.save({
                "model_state_dict": model.state_dict(),
                "classes": classes,
                "val_acc": val_acc,
                "epoch": epoch,
            }, ckpt_path)
            print(f"  -> Saved new best model ({val_acc:.4f}) to {ckpt_path}")
        else:
            epochs_no_improve += 1
            if epochs_no_improve >= cfg.training.early_stopping_patience:
                print("Early stopping triggered.")
                break

    last_path = os.path.join(cfg.paths.checkpoint_dir, "emotion_model_last.pth")
    torch.save({"model_state_dict": model.state_dict(), "classes": classes}, last_path)
    print(f"Training complete. Best val_acc={best_val_acc:.4f}")


if __name__ == "__main__":
    train()
''',

"src/training/evaluate.py": '''"""Evaluation: loss, accuracy, precision/recall/F1, confusion matrix (Phase 6)."""
import torch
from sklearn.metrics import precision_recall_fscore_support, confusion_matrix


@torch.no_grad()
def evaluate(model, dataloader, criterion, device):
    model.eval()
    running_loss, correct, total = 0.0, 0, 0
    all_preds, all_labels = [], []

    for images, labels in dataloader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        loss = criterion(outputs, labels)

        running_loss += loss.item() * images.size(0)
        preds = outputs.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

        all_preds.extend(preds.cpu().numpy().tolist())
        all_labels.extend(labels.cpu().numpy().tolist())

    avg_loss = running_loss / total
    acc = correct / total
    precision, recall, f1, _ = precision_recall_fscore_support(
        all_labels, all_preds, average="macro", zero_division=0
    )
    cm = confusion_matrix(all_labels, all_preds)

    return avg_loss, acc, precision, recall, cm


def print_report(precision, recall, f1, cm, classes):
    print(f"Precision: {precision:.4f}  Recall: {recall:.4f}  F1: {f1:.4f}")
    print("Confusion matrix:")
    print(f"{'':10s}" + "".join(f"{c[:6]:>7s}" for c in classes))
    for i, row in enumerate(cm):
        print(f"{classes[i][:9]:10s}" + "".join(f"{v:7d}" for v in row))
''',

"src/inference/predict.py": '''"""Single-image inference before webcam integration (Phase 8)."""
import argparse
import torch
from PIL import Image

from src.config_loader import load_config
from src.data.transforms import get_eval_transforms
from src.model.efficientnet_b0 import build_model


def load_trained_model(cfg, checkpoint_path, device):
    model = build_model(cfg)
    checkpoint = torch.load(checkpoint_path, map_location=device)
    model.load_state_dict(checkpoint["model_state_dict"])
    model.to(device)
    model.eval()
    classes = checkpoint.get("classes", cfg.classes)
    return model, classes


@torch.no_grad()
def predict_image(model, classes, image_path, transform, device):
    image = Image.open(image_path).convert("RGB")
    tensor = transform(image).unsqueeze(0).to(device)
    logits = model(tensor)
    probs = torch.softmax(logits, dim=1).squeeze(0).cpu().numpy()
    pred_idx = probs.argmax()
    return classes[pred_idx], {c: float(p) for c, p in zip(classes, probs)}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--image", required=True, help="Path to test image")
    parser.add_argument("--checkpoint", default="saved_models/emotion_model_best.pth")
    args = parser.parse_args()

    cfg = load_config()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    model, classes = load_trained_model(cfg, args.checkpoint, device)
    transform = get_eval_transforms(cfg)

    label, probs = predict_image(model, classes, args.image, transform, device)
    print(f"Predicted emotion: {label}")
    for c, p in sorted(probs.items(), key=lambda x: -x[1]):
        print(f"  {c:10s} {p:.4f}")


if __name__ == "__main__":
    main()
''',

"src/inference/face_detector.py": '''"""Face detection + cropping using MediaPipe (Phase 9)."""
import cv2
import mediapipe as mp


class FaceDetector:
    def __init__(self, min_detection_confidence=0.6):
        self.mp_face = mp.solutions.face_detection
        self.detector = self.mp_face.FaceDetection(
            model_selection=1,
            min_detection_confidence=min_detection_confidence,
        )

    def detect_and_crop(self, frame_bgr):
        """Returns the largest detected face crop (BGR np.array) or None."""
        rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
        results = self.detector.process(rgb)
        if not results.detections:
            return None

        h, w, _ = frame_bgr.shape
        best_box, best_area = None, 0
        for det in results.detections:
            box = det.location_data.relative_bounding_box
            x1 = max(int(box.xmin * w), 0)
            y1 = max(int(box.ymin * h), 0)
            bw = int(box.width * w)
            bh = int(box.height * h)
            area = bw * bh
            if area > best_area:
                best_area = area
                best_box = (x1, y1, bw, bh)

        if best_box is None:
            return None

        x1, y1, bw, bh = best_box
        x2, y2 = min(x1 + bw, w), min(y1 + bh, h)
        crop = frame_bgr[y1:y2, x1:x2]
        return crop if crop.size > 0 else None

    def close(self):
        self.detector.close()
''',

"src/inference/temporal_smoothing.py": '''"""Rolling average over last N frames to reduce flicker (Phase 11)."""
from collections import deque
import numpy as np


class TemporalSmoother:
    def __init__(self, classes, window_size=8):
        self.classes = classes
        self.window_size = window_size
        self.buffer = deque(maxlen=window_size)

    def update(self, prob_vector):
        """prob_vector: np.array of shape (num_classes,)"""
        self.buffer.append(prob_vector)
        avg = np.mean(self.buffer, axis=0)
        smoothed_label = self.classes[int(np.argmax(avg))]
        return smoothed_label, avg

    def reset(self):
        self.buffer.clear()
''',

"src/inference/webcam_stream.py": '''"""Real-time webcam emotion detection (Phase 9-11). Entry: /app.py"""
import time
import cv2
import torch
import numpy as np

from src.config_loader import load_config
from src.data.transforms import get_eval_transforms
from src.inference.predict import load_trained_model
from src.inference.face_detector import FaceDetector
from src.inference.temporal_smoothing import TemporalSmoother
from src.backend.api import send_emotion_snapshot


def run_webcam(session_id="local-session", checkpoint_path=None):
    cfg = load_config()
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    checkpoint_path = checkpoint_path or f"{cfg.paths.checkpoint_dir}/emotion_model_best.pth"

    model, classes = load_trained_model(cfg, checkpoint_path, device)
    transform = get_eval_transforms(cfg)
    detector = FaceDetector(min_detection_confidence=cfg.inference.face_detection_confidence)
    smoother = TemporalSmoother(classes, window_size=cfg.inference.smoothing_window)

    cap = cv2.VideoCapture(cfg.inference.webcam_index)
    frame_count = 0

    print("Press 'q' to quit.")
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        frame_count += 1

        if frame_count % cfg.inference.frame_skip == 0:
            face = detector.detect_and_crop(frame)
            if face is not None:
                rgb_face = cv2.cvtColor(face, cv2.COLOR_BGR2RGB)
                from PIL import Image
                pil_face = Image.fromarray(rgb_face)
                tensor = transform(pil_face).unsqueeze(0).to(device)

                with torch.no_grad():
                    logits = model(tensor)
                    probs = torch.softmax(logits, dim=1).squeeze(0).cpu().numpy()

                label, smoothed_probs = smoother.update(probs)

                cv2.putText(frame, label, (20, 40), cv2.FONT_HERSHEY_SIMPLEX,
                            1.0, (0, 255, 0), 2)

                send_emotion_snapshot(
                    session_id=session_id,
                    timestamp=time.time(),
                    probabilities={c: float(p) for c, p in zip(classes, smoothed_probs)},
                )

        cv2.imshow("Facial Emotion Recognition", frame)
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break

    cap.release()
    cv2.destroyAllWindows()
    detector.close()


if __name__ == "__main__":
    run_webcam()
''',

"src/backend/api.py": '''"""Sends emotion probabilities + timestamps to backend (Phase 10)."""
import requests
from src.config_loader import load_config


def send_emotion_snapshot(session_id, timestamp, probabilities):
    cfg = load_config()
    url = cfg.backend.api_base_url + cfg.backend.emotion_endpoint.format(session_id=session_id)
    payload = {"timestamp": timestamp, "probabilities": probabilities}
    try:
        requests.post(url, json=payload, timeout=cfg.backend.timeout_seconds)
    except requests.RequestException as e:
        print(f"[backend] Failed to send emotion snapshot: {e}")
''',

"src/backend/session_store.py": '''"""In-memory / pluggable store for per-session emotion timelines (Phase 10)."""
from collections import defaultdict


class SessionStore:
    def __init__(self):
        self._sessions = defaultdict(list)

    def add_snapshot(self, session_id, timestamp, probabilities):
        self._sessions[session_id].append({
            "timestamp": timestamp,
            "probabilities": probabilities,
        })

    def get_timeline(self, session_id):
        return self._sessions.get(session_id, [])

    def clear_session(self, session_id):
        self._sessions.pop(session_id, None)


session_store = SessionStore()
''',

"src/backend/decision_engine.py": '''"""Combines emotion timeline, conversation history, and RAG context (Phase 12)."""


def summarize_emotion_timeline(timeline):
    """Returns dominant emotion counts and simple stability metric."""
    if not timeline:
        return {}

    from collections import Counter
    dominant = []
    for snap in timeline:
        probs = snap["probabilities"]
        dominant.append(max(probs, key=probs.get))

    counts = Counter(dominant)
    total = len(dominant)
    return {emotion: round(count / total, 3) for emotion, count in counts.items()}


def generate_wellness_assessment(emotion_timeline, conversation_history=None, rag_context=None):
    """
    Skeleton decision engine. Replace with your actual scoring / LLM call.
    emotion_timeline: list of {timestamp, probabilities}
    conversation_history: list of {role, text} or similar
    rag_context: retrieved supporting context/documents
    """
    emotion_summary = summarize_emotion_timeline(emotion_timeline)

    assessment = {
        "emotion_summary": emotion_summary,
        "conversation_turns": len(conversation_history) if conversation_history else 0,
        "rag_context_used": bool(rag_context),
        "notes": "Replace this stub with your real scoring/LLM-based reasoning.",
    }
    return assessment
''',

"tests/test_dataset.py": '''"""Basic sanity tests for dataset loading."""
import os


def test_processed_dirs_exist():
    for split in ["train", "validation", "test"]:
        path = os.path.join("dataset", "processed", split)
        assert os.path.isdir(path), f"Missing directory: {path}"


def test_class_subfolders_exist():
    classes = ["angry", "disgust", "fear", "happy", "neutral", "sad", "surprise"]
    for split in ["train", "validation", "test"]:
        for c in classes:
            path = os.path.join("dataset", "processed", split, c)
            assert os.path.isdir(path), f"Missing class folder: {path}"
''',

"tests/test_model.py": '''"""Basic sanity test that the model builds and runs a forward pass."""
import torch
from src.config_loader import load_config
from src.model.efficientnet_b0 import build_model


def test_model_forward_pass():
    cfg = load_config()
    model = build_model(cfg)
    model.eval()
    dummy = torch.randn(1, 3, cfg.model.input_size, cfg.model.input_size)
    with torch.no_grad():
        out = model(dummy)
    assert out.shape == (1, cfg.model.num_classes)
''',

"tests/test_inference.py": '''"""Basic sanity test for temporal smoothing logic."""
import numpy as np
from src.inference.temporal_smoothing import TemporalSmoother


def test_smoother_returns_valid_label():
    classes = ["angry", "disgust", "fear", "happy", "neutral", "sad", "surprise"]
    smoother = TemporalSmoother(classes, window_size=3)

    probs = np.array([0.1, 0.05, 0.05, 0.6, 0.1, 0.05, 0.05])
    label, avg = smoother.update(probs)

    assert label in classes
    assert avg.shape == (7,)
''',

"train.py": '''"""Root entry point: python train.py"""
from src.training.train import train

if __name__ == "__main__":
    train()
''',

"predict.py": '''"""Root entry point: python predict.py --image path/to/img.jpg"""
from src.inference.predict import main

if __name__ == "__main__":
    main()
''',

"app.py": '''"""Root entry point for webcam + backend pipeline: python app.py"""
from src.inference.webcam_stream import run_webcam

if __name__ == "__main__":
    run_webcam(session_id="demo-session")
''',
}

# Directories that must exist even if empty (dataset raw/processed splits, logs, notebooks, saved_models)
EMPTY_DIRS = [
    "dataset/raw/fer2013",
    "dataset/raw/ckplus",
    "dataset/raw/rafdb",
    "notebooks",
    "saved_models",
    "logs/train_logs",
    "logs/tensorboard",
]

for split in ["train", "validation", "test"]:
    for cls in CLASSES:
        EMPTY_DIRS.append(f"dataset/processed/{split}/{cls}")


def create_structure(target_dir):
    os.makedirs(target_dir, exist_ok=True)

    for rel_dir in EMPTY_DIRS:
        full_dir = os.path.join(target_dir, rel_dir)
        os.makedirs(full_dir, exist_ok=True)
        # keep empty dataset folders tracked in git
        gitkeep = os.path.join(full_dir, ".gitkeep")
        if not os.path.exists(gitkeep):
            open(gitkeep, "w").close()

    for rel_path, content in FILES.items():
        full_path = os.path.join(target_dir, rel_path)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, "w") as f:
            f.write(content)

    print(f"Project structure created at: {os.path.abspath(target_dir)}")
    print(f"Total files written: {len(FILES)}")
    print(f"Total directories ensured: {len(EMPTY_DIRS)}")
    print("\nNext steps:")
    print(f"  cd {target_dir}")
    print("  pip install -r requirements.txt")
    print("  # add data under dataset/raw/, populate dataset/processed/<split>/<class>/")
    print("  python train.py")


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else "fer_project"
    create_structure(target)